name: caiman-online
channels:
 - conda-forge
dependencies:
 - numpy
 - python
 - pip
 - websockets
 - websocket-client
 - matplotlib
 - pandas
 - seaborn
 - xarray
 - scikit-learn
 - scipy
 - tifffile
 - jupyterlab
 - notebook
 - caiman = 1.8.5
 - h5py=2.10.0 # attempted to pin to fix file saving issue
 - pip:
   - scanimage-tiff-reader