name: caiman-online-gpu
channels:
 - conda-forge
 - anaconda
dependencies:
 - numpy
 - python
 - pip
 - websockets
 - websocket-client
 - matplotlib
 - pandas
 - seaborn
 - xarray
 - scikit-learn
 - scipy
 - tifffile
 - jupyterlab
 - notebook
 - caiman=1.8.5
 - opencv
 - cudnn
 - cudatoolkit
 - keras
 - pip:
   - scanimage-tiff-reader
   - tensorflow-gpu==2.2.0
   - tensorflow-addons==0.10.0