name: caiman-online-test2
channels:
 - conda-forge
dependencies:
 - numpy=1.14
 - python
 - caiman
 - pip
 - websockets
 - websocket-client
 - matplotlib
 - pandas
 - seaborn
 - hdmf=1.3.3
 - pip:
   - scanimage-tiff-reader
   